import { CourseModule, TrainingStage } from "./types";

export const curriculumModules: CourseModule[] = [
  {
    id: "general-ledger",
    code: "GL-101",
    title: "General Ledger (GL)",
    shortDesc: "Chart of accounts, ledger configurations, journal operations, allocations, and multi-currency consolidation.",
    longDesc: "The core engine of Oracle Fusion Financials. Learn how to configure Enterprise Structures, design scalable multi-segment Charts of Accounts (COA), define accounting calendars, currencies, Primary and Secondary Ledgers, and automate complex recurring journals and mass allocations.",
    iconName: "BookOpen",
    topics: [
      "Enterprise Structure & Multi-Org Architecture",
      "Chart of Accounts (COA) Structure & Segment Qualifiers",
      "Accounting Calendars, Currencies & Conversion Rates",
      "Primary, Secondary & Reporting Ledgers Configuration",
      "Journal Batches, Manual & Spreadsheet (ADFdi) Uploads",
      "Recurring Journals, Statistical Journals & Allocations",
      "Financial Reporting Studio (FRS) & Smart View integration",
      "Month-end and Year-end Financial Closing Procedures",
    ],
    practicalExercises: [
      "Set up a global multinational enterprise with US and EMEA subsidiaries.",
      "Design and deploy an 8-segment Chart of Accounts with security rules.",
      "Configure cross-validation rules and account alias lists.",
      "Upload 500+ line journal entries using ADFdi spreadsheet integrator.",
      "Execute multi-currency revaluation and balance consolidation.",
    ],
    businessProcess: "Record-to-Report (R2R)",
    outcome: "Ability to configure financial ledgers from scratch and manage period-close accounting with full audit compliance.",
  },
  {
    id: "accounts-payable",
    code: "AP-201",
    title: "Accounts Payable (AP)",
    shortDesc: "Supplier management, invoice processing, matching rules, payment automation, and withholding taxes.",
    longDesc: "Master end-to-end invoice automation and supplier payments. Understand 2-way, 3-way, and 4-way matching against purchase orders, automated invoice scanning, payment process requests (PPR), prepayment settlements, and electronic funds transfers (EFT).",
    iconName: "CreditCard",
    topics: [
      "Supplier Model, Procurement Agents & Business Units",
      "Invoice Types: Standard, Prepayment, Debit/Credit Memo, Retainage",
      "Invoice Tolerances, Holds & Approval Management Engine (AME)",
      "2-Way, 3-Way & 4-Way Matching Workflows",
      "Automated Payment Process Requests (PPR) & Payment Formats",
      "Withholding Tax, 1099 Reporting & Self-Assessed Taxes",
      "Payables to General Ledger Reconciliation",
      "Period Close Diagnostics & Unaccounted Transactions Cleanup",
    ],
    practicalExercises: [
      "Register global suppliers with multiple payment sites and bank accounts.",
      "Process 3-way matched supplier invoices against receiving documents.",
      "Resolve variance holds and tolerance exceptions.",
      "Run an automated batch payment cycle with bank file output.",
      "Reconcile Payables Trial Balance against GL summary balances.",
    ],
    businessProcess: "Procure-to-Pay (P2P)",
    outcome: "Configure comprehensive vendor payment cycles and handle complex invoice approval rules and bank integrations.",
  },
  {
    id: "accounts-receivable",
    code: "AR-301",
    title: "Accounts Receivable (AR)",
    shortDesc: "Customer data models, transaction creation, auto-invoicing, receipt processing, and disputes.",
    longDesc: "Understand revenue generation and billing management. Configure customer profiles, transaction types, auto-invoicing from upstream order systems, manual & lockbox receipt processing, receipt reversal, and aging analytics.",
    iconName: "Receipt",
    topics: [
      "Customer Account Architecture: Parties, Accounts, and Sites",
      "Transaction Types, Sources & Memo Lines",
      "Auto-Invoice Engine & Interface Error Rectification",
      "Standard Receipts, Manual Receipts & Lockbox Ingestion",
      "Automatic Cash Application & Remittance Batches",
      "Credit Memo Workflows & Customer Dispute Processing",
      "Aging Reports, Collection Management & Statement Delivery",
      "Subledger Accounting (SLA) Rules for Receivables",
    ],
    practicalExercises: [
      "Create multi-tier customer relationships with separate billing and shipping locations.",
      "Simulate AutoInvoice import of sales order lines with accounting date derivations.",
      "Configure automatic receipt matching algorithms.",
      "Set up customer statement cycles and calculate overdue interest.",
      "Perform AR to GL trial balance reconciliation.",
    ],
    businessProcess: "Order-to-Cash (O2C)",
    outcome: "Deploy customer invoicing systems with seamless revenue posting and automated collection processing.",
  },
  {
    id: "cash-management",
    code: "CE-401",
    title: "Cash Management (CE)",
    shortDesc: "Bank structure modeling, automatic statement reconciliation, cash pooling, and liquidity forecasting.",
    longDesc: "Bridge the gap between internal ledgers and commercial banking. Configure internal bank accounts, parse MT940 and BAI2 electronic bank statements, establish automatic matching rules, and generate real-time daily cash position sheets.",
    iconName: "Landmark",
    topics: [
      "Bank, Branch & Account Hierarchies and Legal Entity Association",
      "Bank Statement Ingestion (MT940, BAI2, CAMT.053)",
      "Automatic Reconciliation Tolerance & Parsing Rules",
      "Manual Reconciliation & Exception Clearing",
      "Bank Account Transfers & Internal Intercompany Clearing",
      "Cash Positioning, Liquidity Worksheets & Forecasting",
      "Cash Management Integration with AP, AR, and Payroll",
    ],
    practicalExercises: [
      "Configure internal multi-currency bank accounts with authorized payment signers.",
      "Import live simulated BAI2 bank statements.",
      "Build auto-reconciliation rules matching statement lines to AP payments and AR receipts.",
      "Create an end-of-day bank transfer across treasury accounts.",
      "Generate an automated 30-day liquidity cash forecast report.",
    ],
    businessProcess: "Treasury & Bank Liquidity Management",
    outcome: "Execute enterprise bank integration, end-to-end auto-reconciliation, and multi-currency liquidity reporting.",
  },
  {
    id: "fixed-assets",
    code: "FA-501",
    title: "Fixed Assets (FA)",
    shortDesc: "Asset lifecycle, asset books, depreciation methods, transfers, impairments, and retirements.",
    longDesc: "Track company capital investments from capitalization to retirement. Configure Corporate and Tax Asset Books, asset categories, straight-line and accelerated depreciation methods, Mass Additions from AP, physical inventory tracking, and CIP asset capitalization.",
    iconName: "Building2",
    topics: [
      "Asset Books: Corporate, Tax, and Budget Books",
      "Asset Categories, Prorate Conventions & Depreciation Methods",
      "Asset Additions: Manual, CIP, and Mass Additions from AP & Projects",
      "Depreciation Run, Projections & What-If Depreciation Scenarios",
      "Asset Adjustments, Transfers, Impairments & Revaluations",
      "Retirements, Reinstatements & Gain/Loss Calculations",
      "Fixed Assets Subledger Accounting to GL Reconciliation",
    ],
    practicalExercises: [
      "Build Corporate and Federal Tax Books linked to separate GL ledgers.",
      "Track Construction-in-Progress (CIP) equipment and capitalize into operational assets.",
      "Process automated mass addition lines fed from Accounts Payable invoices.",
      "Execute monthly depreciation run and analyze journal distributions.",
      "Conduct partial and complete asset retirements with scrap and sale proceeds.",
    ],
    businessProcess: "Acquire-to-Retire (A2R)",
    outcome: "Implement end-to-end corporate asset registers, automated depreciation engines, and multi-book tax tracking.",
  },
  {
    id: "expenses",
    code: "EX-601",
    title: "Fusion Expenses",
    shortDesc: "Mobile expense capture, policy compliance, corporate credit card integration, and reimbursements.",
    longDesc: "Modern employee expense management. Configure expense templates, itemization policies, daily per-diem rates, corporate card feed processing, supervisory approval hierarchies, and direct integration with Accounts Payable for rapid employee reimbursements.",
    iconName: "FileSpreadsheet",
    topics: [
      "Expense Templates, Types & Expense Field Rules",
      "Corporate Credit Card Integration (Visa, Mastercard, Amex)",
      "Expense Auditing Rules, Violation Limits & Receipt Thresholds",
      "Approval Hierarchies via Supervisory Hierarchy & BPM Worklist",
      "Employee Reimbursement Processing via AP Payment Engine",
      "Mileage and Daily Allowance (Per Diem) Schedules",
    ],
    practicalExercises: [
      "Configure Travel & Entertainment expense templates with per-meal limit caps.",
      "Simulate corporate credit card transaction import and cardholder reconciliation.",
      "Establish automated approval routing based on expense threshold bands.",
      "Export approved expense reports into Accounts Payable for payment processing.",
    ],
    businessProcess: "Employee Spend & Reimbursement",
    outcome: "Deploy frictionless expense reporting with policy audit automation and payment execution.",
  },
  {
    id: "tax",
    code: "TX-701",
    title: "Oracle Fusion Tax (ZX)",
    shortDesc: "Global tax regime setup, tax jurisdictions, recovery rates, and automatic tax determination.",
    longDesc: "A centralized tax engine that calculates and applies correct transaction taxes across all modules. Configure Tax Regimes, Taxes, Tax Statuses, Tax Rates, and complex condition-based Tax Determination Rules covering VAT, GST, and US Sales & Use Tax.",
    iconName: "Scale",
    topics: [
      "Tax Configuration Architecture & Foundation Data",
      "Tax Regimes, Taxes, Jurisdictions & Recovery Rates",
      "Tax Determination Rules: Direct Rate, Applicability & Status Rules",
      "Tax Reporting Types, Boxes & Statutory Output Preparation",
      "Integration with AP Invoices, AR Billing, and PO Purchasing",
      "Vertex / Avalara external tax partner integration concepts",
    ],
    practicalExercises: [
      "Configure a VAT regime with standard, reduced, and zero-rated tax statuses.",
      "Build a rule deriving tax rates based on Ship-From vs Ship-To geographic locations.",
      "Verify automated tax calculation during AP invoice entry and AR invoicing.",
      "Extract statutory tax box reporting for quarterly filing audits.",
    ],
    businessProcess: "Statutory Tax Governance",
    outcome: "Architect compliant, multi-jurisdiction indirect tax determination across purchase and sales cycles.",
  },
  {
    id: "reporting-otbi",
    code: "REP-801",
    title: "Financial Reporting & OTBI Analytics",
    shortDesc: "Real-time transactional business intelligence (OTBI), Financial Reporting Studio (FRS), and Smart View.",
    longDesc: "Executive reporting and real-time visibility. Learn how to craft multi-dimensional financial reports using Oracle Financial Reporting Studio, build live operational dashboards using Oracle Transactional Business Intelligence (OTBI), and automate Excel analysis using Smart View.",
    iconName: "BarChart3",
    topics: [
      "Oracle Financial Reporting Studio (FRS) Design & Deployment",
      "Smart View for MS Office: Ad-Hoc GL Analysis & Report Distribution",
      "Oracle Transactional Business Intelligence (OTBI) Subject Areas",
      "Creating Drill-Through Operational Dashboards and KPI Tiles",
      "BI Publisher Data Models, SQL Queries & Custom Pixel-Perfect Layouts",
      "Report Scheduling, Bursting & Email Delivery to Executives",
    ],
    practicalExercises: [
      "Build an executive Balance Sheet and Income Statement with drill-down to subledger.",
      "Connect Microsoft Excel to live Fusion Cloud via Smart View for interactive budget variance analysis.",
      "Design an AP aging and pending hold analysis dashboard in OTBI with interactive filters.",
      "Schedule automated weekly automated report bursting to financial department heads.",
    ],
    businessProcess: "Analytics & Executive Decision Support",
    outcome: "Produce executive financial statements, real-time operational analytics, and automated reporting distribution.",
  },
  {
    id: "business-processes",
    code: "BP-901",
    title: "End-to-End Business Processes (P2P, O2C, R2R)",
    shortDesc: "Cross-functional enterprise workflows tying procurement, inventory, receivables, and ledger accounting together.",
    longDesc: "True enterprise consultants do not work in module silos. This module integrates everything into real-world corporate execution: Procure-to-Pay (P2P), Order-to-Cash (O2C), and Record-to-Report (R2R), teaching you how data flows and settles across systems.",
    iconName: "GitMerge",
    topics: [
      "Procure-to-Pay (P2P): Requisition > PO > Receipt > Invoice > Payment > GL",
      "Order-to-Cash (O2C): Sales Order > Fulfillment > Invoicing > Receipt > Bank > GL",
      "Record-to-Report (R2R): Subledger Transactions > SLA > GL Posting > Consolidation > Reporting",
      "Intercompany Accounting & Centralized Corporate Allocations",
      "Cross-Module Troubleshooting & Interface Diagnostics",
    ],
    practicalExercises: [
      "Execute a live full-lifecycle P2P scenario from purchasing demand to final bank clearing.",
      "Run an entire O2C order lifecycle with revenue recognition and cash receipt matching.",
      "Perform month-end closing sequencing across AP, AR, FA, and GL.",
      "Trace an orphaned transaction and resolve subledger accounting errors.",
    ],
    businessProcess: "Cross-Functional Enterprise Architecture",
    outcome: "Possess holistic, cross-module business fluency that sets top-tier functional consultants apart.",
  },
  {
    id: "configuration-concepts",
    code: "CFG-1001",
    title: "Functional Configuration & Rapid Implementation",
    shortDesc: "Functional Setup Manager (FSM), Rapid Implementation Spreadsheets, and Environment Migration.",
    longDesc: "Understand how real Oracle Fusion Cloud projects are delivered. Explore Functional Setup Manager (FSM), configuring business units, security roles, Rapid Implementation (RI) workbooks, and migrating configuration between Dev, Test, and Production pods.",
    iconName: "Settings2",
    topics: [
      "Functional Setup Manager (FSM) Tasks, Offerings & Functional Areas",
      "Rapid Implementation (RI) Templates for COA, Ledgers, and Business Units",
      "Security Console: Job Roles, Duty Roles, Data Access & Segregation of Duties (SoD)",
      "Configuration Packages: Export and Import between Cloud Pods",
      "Environment Lifecycle: Dev, Test, Stage, and Production Management",
    ],
    practicalExercises: [
      "Populate and upload an official Rapid Implementation spreadsheet to generate a complete enterprise structure.",
      "Create custom Job Roles with restricted read/write data security access.",
      "Export an FSM configuration package and import into a secondary test environment.",
      "Audit role provisioning for compliance with internal control policies.",
    ],
    businessProcess: "ERP Implementation & Pod Governance",
    outcome: "Deliver professional client setups swiftly using standard Oracle methodology and automated tools.",
  },
  {
    id: "interview-preparation",
    code: "CAR-1101",
    title: "Oracle Fusion Consultant Interview Preparation",
    shortDesc: "Scenario-based interview coaching, project resume crafting, technical rounds, and client presentation skills.",
    longDesc: "Translate technical learning into career success. Learn how to explain client business problems, articulate project implementation methodologies (OUM/True Cloud), handle technical challenge questions, and present yourself confidently in consulting interviews.",
    iconName: "Award",
    topics: [
      "Structuring Project Experience: Greenfield vs Migration vs Support roles",
      "High-Frequency Technical & Scenario Interview Questions with Model Answers",
      "Explaining Subledger Accounting (SLA) & Custom Rule Architectures to Interviewers",
      "Client Facing Soft Skills: Requirement Gathering & Gap Analysis Workshops",
      "LinkedIn Profile & Targeted Oracle Functional Consultant Resume Optimization",
      "1-on-1 Mock Interview Rounds with Detailed Personal Feedback",
    ],
    practicalExercises: [
      "Draft a professional ERP project portfolio summarizing 2 simulated implementation projects.",
      "Complete a live 45-minute technical mock interview assessing P2P, O2C, and R2R depth.",
      "Receive line-by-line resume critique optimized for Applicant Tracking Systems (ATS).",
      "Present a 10-minute client requirement workshop simulation.",
    ],
    businessProcess: "Career Launch & Professional Placement",
    outcome: "Interview with high authority, deep scenario comprehension, and genuine technical credibility.",
  },
];

export const trainingStages: TrainingStage[] = [
  {
    step: "01",
    title: "Foundations & Architecture",
    duration: "Phase 1",
    description: "Understand Oracle Cloud SaaS architecture, enterprise structures, multi-org concepts, and navigation fundamentals.",
    modulesCovered: ["Enterprise Structure", "Functional Setup Manager", "Navigation Basics"],
    keyOutcome: "Confidence in cloud system layout and organizational hierarchy modeling.",
  },
  {
    step: "02",
    title: "Core Financial Ledgers",
    duration: "Phase 2",
    description: "Deep dive into General Ledger design: Chart of accounts, primary/secondary ledgers, calendars, and currency handling.",
    modulesCovered: ["General Ledger (GL)", "ADFdi Journal Uploads", "Financial Closing"],
    keyOutcome: "Ability to configure financial ledgers from scratch and manage period-close accounting.",
  },
  {
    step: "03",
    title: "Subledger Execution (AP & AR)",
    duration: "Phase 3",
    description: "Operate payables and receivables engines with supplier/customer models, matching tolerances, and payment runs.",
    modulesCovered: ["Accounts Payable", "Accounts Receivable", "Cash Application"],
    keyOutcome: "Hands-on execution of daily corporate transactional volumes and invoice matching.",
  },
  {
    step: "04",
    title: "Cash, Assets & Specialized Engines",
    duration: "Phase 4",
    description: "Master bank auto-reconciliation, liquidity management, asset lifecycle accounting, employee expenses, and indirect taxes.",
    modulesCovered: ["Cash Management", "Fixed Assets", "Expenses", "Fusion Tax"],
    keyOutcome: "Mastery of treasury reconciliation, asset capitalization, and global tax rules.",
  },
  {
    step: "05",
    title: "Cross-Module Business Processes",
    duration: "Phase 5",
    description: "Execute end-to-end P2P, O2C, and R2R corporate workflows with SLA rules and subledger-to-GL reconciliations.",
    modulesCovered: ["Procure-to-Pay", "Order-to-Cash", "Record-to-Report", "SLA Rules"],
    keyOutcome: "Holistic comprehension of how multinational enterprises operate seamlessly on Oracle Cloud.",
  },
  {
    step: "06",
    title: "Reporting & Career Readiness",
    duration: "Phase 6",
    description: "Construct OTBI analytics dashboards, Smart View models, followed by rigorous interview prep and resume polishing.",
    modulesCovered: ["OTBI Analytics", "Smart View / FRS", "Mock Interviews", "Resume Workshops"],
    keyOutcome: "Ready to sit for Oracle certification and interview confidently for consultant roles.",
  },
];
